version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      # Install dependencies into the 'package' folder
      - mkdir package
      - pip install -r requirements.txt -t package
  build:
    commands:
      - echo Copying source files...
      # Copy your Lambda function code into the package folder.
      - cp extract_fields_to_csv.py package/
      - echo Creating deployment package...
      # Change directory into 'package' and zip all contents.
      - cd package && zip -r ../lambda_deploy.zip .
artifacts:
  files:
    - lambda_deploy.zip
