version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      # Install all dependencies into the current directory (.)
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping the source and dependencies..."
      # Zip everything in the current directory, including extract_fields_to_csv.py and installed packages
      - zip -r lambda_deploy.zip .
artifacts:
  files:
    - lambda_deploy.zip
